POST http://localhost:3001/api/notes/ 
Content-Type: application/json

{
    "content":"contenido1"
}

###

POST http://localhost:3001/api/notes/ 
Content-Type: application/json

{
    "important": true
}

###
POST http://localhost:3001/api/notes/ 
Content-Type: application/json

{
    "content":"contenido1",
    "important": true
}